// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Lightkey-Control

#ifndef _LIGHTKEY_CONTROL_UI_H
#define _LIGHTKEY_CONTROL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_CueButton1;
extern lv_obj_t * ui_lblCue1;
extern lv_obj_t * ui_CueButton2;
extern lv_obj_t * ui_lblCue2;
extern lv_obj_t * ui_CueButton3;
extern lv_obj_t * ui_lblCue3;
extern lv_obj_t * ui_CueButton4;
extern lv_obj_t * ui_lblCue4;
extern lv_obj_t * ui_CueButton5;
extern lv_obj_t * ui_lblCue5;
extern lv_obj_t * ui_CueButton6;
extern lv_obj_t * ui_lblCue6;
extern lv_obj_t * ui_HomeButton1;
void ui_event_SettingsButton1(lv_event_t * e);
extern lv_obj_t * ui_SettingsButton1;
extern lv_obj_t * ui_WifiIcon1;
extern lv_obj_t * ui_MidiIcon1;
extern lv_obj_t * ui_tip1;
extern lv_obj_t * ui_lblTip1;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
void ui_event_HomeButton2(lv_event_t * e);
extern lv_obj_t * ui_HomeButton2;
extern lv_obj_t * ui_SettingsButton2;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_lblSSID;
void ui_event_txtSSID(lv_event_t * e);
extern lv_obj_t * ui_txtSSID;
extern lv_obj_t * ui_lblPassword;
void ui_event_txtPassword(lv_event_t * e);
extern lv_obj_t * ui_txtPassword;
void ui_event_ConnectButton(lv_event_t * e);
extern lv_obj_t * ui_ConnectButton;
extern lv_obj_t * ui_lblConnectBtn;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_lblRemoteIP;
void ui_event_txtRemoteIP(lv_event_t * e);
extern lv_obj_t * ui_txtRemoteIP;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_SaveButton;
extern lv_obj_t * ui_lblSaveButton;
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui_WifiIcon2;
extern lv_obj_t * ui_MidiIcon2;
extern lv_obj_t * ui_tip2;
extern lv_obj_t * ui_lblTip2;
extern lv_obj_t * ui____initial_actions0;

extern int login_flag;

LV_IMG_DECLARE(ui_img_icn_home_png);    // assets/icn_home.png
LV_IMG_DECLARE(ui_img_icn_settings_wht_sm_png);    // assets/icn_settings_wht_sm.png
LV_IMG_DECLARE(ui_img_443613123);    // assets/icons8-wifi-50.png
LV_IMG_DECLARE(ui_img_2037930486);    // assets/icons8-midi-connector-male-48.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
