// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Lightkey-Control

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x323232), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CueButton1 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_CueButton1, 100);
    lv_obj_set_height(ui_CueButton1, 100);
    lv_obj_set_x(ui_CueButton1, 30);
    lv_obj_set_y(ui_CueButton1, 60);
    lv_obj_add_flag(ui_CueButton1, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CueButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblCue1 = lv_label_create(ui_CueButton1);
    lv_obj_set_width(ui_lblCue1, 88);
    lv_obj_set_height(ui_lblCue1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblCue1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblCue1, "Cue 1");
    lv_obj_set_style_text_align(ui_lblCue1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblCue1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CueButton2 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_CueButton2, 100);
    lv_obj_set_height(ui_CueButton2, 100);
    lv_obj_set_x(ui_CueButton2, 0);
    lv_obj_set_y(ui_CueButton2, 60);
    lv_obj_set_align(ui_CueButton2, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_CueButton2, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CueButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblCue2 = lv_label_create(ui_CueButton2);
    lv_obj_set_width(ui_lblCue2, 88);
    lv_obj_set_height(ui_lblCue2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblCue2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblCue2, "Cue 2");
    lv_obj_set_style_text_align(ui_lblCue2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblCue2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CueButton3 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_CueButton3, 100);
    lv_obj_set_height(ui_CueButton3, 100);
    lv_obj_set_x(ui_CueButton3, -30);
    lv_obj_set_y(ui_CueButton3, 60);
    lv_obj_set_align(ui_CueButton3, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_CueButton3, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CueButton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblCue3 = lv_label_create(ui_CueButton3);
    lv_obj_set_width(ui_lblCue3, 88);
    lv_obj_set_height(ui_lblCue3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblCue3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblCue3, "Cue 3");
    lv_obj_set_style_text_align(ui_lblCue3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblCue3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CueButton4 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_CueButton4, 100);
    lv_obj_set_height(ui_CueButton4, 100);
    lv_obj_set_x(ui_CueButton4, 30);
    lv_obj_set_y(ui_CueButton4, -30);
    lv_obj_set_align(ui_CueButton4, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_CueButton4, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CueButton4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblCue4 = lv_label_create(ui_CueButton4);
    lv_obj_set_width(ui_lblCue4, 88);
    lv_obj_set_height(ui_lblCue4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblCue4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblCue4, "Cue 4");
    lv_obj_set_style_text_align(ui_lblCue4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblCue4, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CueButton5 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_CueButton5, 100);
    lv_obj_set_height(ui_CueButton5, 100);
    lv_obj_set_x(ui_CueButton5, 0);
    lv_obj_set_y(ui_CueButton5, -30);
    lv_obj_set_align(ui_CueButton5, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_CueButton5, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CueButton5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblCue5 = lv_label_create(ui_CueButton5);
    lv_obj_set_width(ui_lblCue5, 88);
    lv_obj_set_height(ui_lblCue5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblCue5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblCue5, "Cue 5");
    lv_obj_set_style_text_align(ui_lblCue5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblCue5, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CueButton6 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_CueButton6, 100);
    lv_obj_set_height(ui_CueButton6, 100);
    lv_obj_set_x(ui_CueButton6, -30);
    lv_obj_set_y(ui_CueButton6, -30);
    lv_obj_set_align(ui_CueButton6, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_CueButton6, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CueButton6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblCue6 = lv_label_create(ui_CueButton6);
    lv_obj_set_width(ui_lblCue6, 88);
    lv_obj_set_height(ui_lblCue6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblCue6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblCue6, "Cue 6");
    lv_obj_set_style_text_align(ui_lblCue6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblCue6, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeButton1 = lv_imgbtn_create(ui_Screen1);
    lv_imgbtn_set_src(ui_HomeButton1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_icn_home_png, NULL);
    lv_imgbtn_set_src(ui_HomeButton1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_icn_home_png, NULL);
    lv_imgbtn_set_src(ui_HomeButton1, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_icn_home_png, NULL);
    lv_obj_set_height(ui_HomeButton1, 35);
    lv_obj_set_width(ui_HomeButton1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_HomeButton1, 10);
    lv_obj_set_y(ui_HomeButton1, 10);
    lv_obj_set_style_img_recolor(ui_HomeButton1, lv_color_hex(0x84C0F1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_HomeButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_HomeButton1, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor_opa(ui_HomeButton1, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor(ui_HomeButton1, lv_color_hex(0x5A5A5A), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_img_recolor_opa(ui_HomeButton1, 200, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_SettingsButton1 = lv_imgbtn_create(ui_Screen1);
    lv_imgbtn_set_src(ui_SettingsButton1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_icn_settings_wht_sm_png, NULL);
    lv_imgbtn_set_src(ui_SettingsButton1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_icn_settings_wht_sm_png, NULL);
    lv_imgbtn_set_src(ui_SettingsButton1, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_icn_settings_wht_sm_png, NULL);
    lv_obj_set_height(ui_SettingsButton1, 35);
    lv_obj_set_width(ui_SettingsButton1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_SettingsButton1, -10);
    lv_obj_set_y(ui_SettingsButton1, 10);
    lv_obj_set_align(ui_SettingsButton1, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_style_img_recolor(ui_SettingsButton1, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor_opa(ui_SettingsButton1, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor(ui_SettingsButton1, lv_color_hex(0x5A5A5A), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_img_recolor_opa(ui_SettingsButton1, 200, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_WifiIcon1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_WifiIcon1, &ui_img_443613123);
    lv_obj_set_width(ui_WifiIcon1, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_WifiIcon1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_WifiIcon1, -20);
    lv_obj_set_y(ui_WifiIcon1, 3);
    lv_obj_set_align(ui_WifiIcon1, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_WifiIcon1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WifiIcon1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_WifiIcon1, 150);

    ui_MidiIcon1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_MidiIcon1, &ui_img_2037930486);
    lv_obj_set_width(ui_MidiIcon1, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_MidiIcon1, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_MidiIcon1, 20);
    lv_obj_set_y(ui_MidiIcon1, 3);
    lv_obj_set_align(ui_MidiIcon1, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_MidiIcon1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_MidiIcon1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_MidiIcon1, 150);

    ui_tip1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_tip1, 266);
    lv_obj_set_height(ui_tip1, 28);
    lv_obj_set_x(ui_tip1, 0);
    lv_obj_set_y(ui_tip1, -132);
    lv_obj_set_align(ui_tip1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tip1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_tip1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_tip1, lv_color_hex(0x313031), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tip1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTip1 = lv_label_create(ui_tip1);
    lv_obj_set_width(ui_lblTip1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTip1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblTip1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTip1, "Connecting to WiFi...");
    lv_obj_set_style_text_color(ui_lblTip1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTip1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SettingsButton1, ui_event_SettingsButton1, LV_EVENT_ALL, NULL);

}
